### ISSUE TITLE
Should we consider the balance of the user

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-telegram#45]
Should we publish the message even if the user doesn't have balance. 

One user could post an order with the funds to back it up

**Comment by bh2smith** [comment]
> Should we publish the message even if the user doesn't have balance.

I would say yes to this because then people could post sneaky orders, but placing orders first (which are not shows in telegram) and then depositing. Thus, essentially having their order placed without anyone knowing.

That being said, however, it will be weird when we start placing strategy orders with "infinite" sell amounts.

**Comment by anxolin** [comment]
Yep, I'll close then for now ;)
